version: "2"
run:
  timeout: 3m
  go: "1.25"
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocritic
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-use-default: false
